version: "3.8"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: golang-app
    ports:
      - "8080:8080"  # ánh xạ cổng host:container
    environment:
      DB_HOST: localhost
      DB_PORT: 3307
      DB_USER: root
      DB_PASSWORD: 123456
      DB_NAME: golang_db
    depends_on:
      - db

  db:
    image: mysql:8.0
    container_name: mysql-db
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_DATABASE: golang_db
      MYSQL_USER: merchant
      MYSQL_PASSWORD: 123456
    ports:
      - "3307:3306"  # ánh xạ cổng host:container
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
