version: "3.8"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: golang-app
    ports:
      - "${APP_PORT}:${APP_PORT}"
    tty: true
    environment:
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}
    depends_on:
      - db

  db:
    image: mysql:8.0
    container_name: mysql-db
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: ${MYSQL_ALLOW_EMPTY_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "${PORT_CTN_CONN}:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
